#!/usr/bin/env bun
/**
 * Fetches TTC static data and writes src/assets/ttc-baked.ts.
 * Run: bun scripts/bake-ttc.ts
 */

const BASE = 'https://transit.ttc.com.ge/pis-gateway/api';
const API_KEY = 'c0a2f304-551a-4d08-b8df-2c53ecd57f9f';
const headers = { 'x-api-key': API_KEY };

const ROUTES = {
  '380': { id: '1:R97505', toKojori: '0:01', toTbilisi: '1:01' },
  '316': { id: '1:R98445', toKojori: '1:01', toTbilisi: '0:01' },
} as const;

const STOP_IDS = ['1:3932', '1:853', '1:2856', '1:4181', '1:3782', '1:3078', '1:3537'];

type BusLine = '380' | '316';
type Direction = 'toKojori' | 'toTbilisi';
type RouteKey = `${BusLine}_${Direction}`;

function sleep(ms: number) {
  return new Promise(resolve => setTimeout(resolve, ms));
}

async function get(path: string) {
  await sleep(800);
  const res = await fetch(`${BASE}${path}`, { headers });
  if (!res.ok) throw new Error(`HTTP ${res.status} for ${path}`);
  return res.json();
}

async function fetchSchedule(routeId: string, patternSuffix: string) {
  return get(`/v3/routes/${routeId}/schedule?patternSuffix=${patternSuffix}&locale=en`);
}

async function fetchStops(routeId: string, patternSuffix: string) {
  return get(`/v3/routes/${routeId}/stops-of-patterns?patternSuffixes=${patternSuffix}&locale=en`);
}

async function fetchPolyline(routeId: string, patternSuffix: string) {
  return get(`/v3/routes/${routeId}/polylines?patternSuffixes=${patternSuffix}`);
}

async function fetchStopDetails(stopId: string) {
  return get(`/v2/stops/${stopId}?locale=en`);
}

console.log('Baking TTC data…');

const schedules: Record<RouteKey, unknown> = {} as Record<RouteKey, unknown>;
const polylines: Record<RouteKey, string> = {} as Record<RouteKey, string>;
const stops: Record<RouteKey, unknown> = {} as Record<RouteKey, unknown>;
const stopNames: Record<string, string> = {};

// Schedules — 4 sequential requests
for (const [bus, route] of Object.entries(ROUTES) as [BusLine, typeof ROUTES['380']][]) {
  for (const dir of ['toKojori', 'toTbilisi'] as Direction[]) {
    const key: RouteKey = `${bus}_${dir}`;
    const patternSuffix = route[dir];
    console.log(`  schedule ${key}…`);
    schedules[key] = await fetchSchedule(route.id, patternSuffix);
  }
}

// Stops — 4 sequential requests
for (const [bus, route] of Object.entries(ROUTES) as [BusLine, typeof ROUTES['380']][]) {
  for (const dir of ['toKojori', 'toTbilisi'] as Direction[]) {
    const key: RouteKey = `${bus}_${dir}`;
    const patternSuffix = route[dir];
    console.log(`  stops ${key}…`);
    stops[key] = await fetchStops(route.id, patternSuffix);
  }
}

// Polylines — 4 sequential requests
for (const [bus, route] of Object.entries(ROUTES) as [BusLine, typeof ROUTES['380']][]) {
  for (const dir of ['toKojori', 'toTbilisi'] as Direction[]) {
    const key: RouteKey = `${bus}_${dir}`;
    const patternSuffix = route[dir];
    console.log(`  polyline ${key}…`);
    const raw = await fetchPolyline(route.id, patternSuffix) as Record<string, { encodedValue?: string }>;
    const encodedValue = raw[patternSuffix]?.encodedValue;
    if (!encodedValue) throw new Error(`No encodedValue for ${key}`);
    polylines[key] = encodedValue;
  }
}

// Stop names — sequential
for (const stopId of STOP_IDS) {
  console.log(`  stop name ${stopId}…`);
  const data = await fetchStopDetails(stopId) as { name?: string };
  if (data.name) stopNames[stopId] = data.name;
}

const bakedAt = new Date().toISOString();

const output = `// AUTO-GENERATED by scripts/bake-ttc.ts — do not edit manually.
// Last baked: ${bakedAt}
// Re-run: bun scripts/bake-ttc.ts

export const BAKED_AT = '${bakedAt}';

export const BAKED_SCHEDULES = ${JSON.stringify(schedules, null, 2)} as const;

export const BAKED_POLYLINES: Record<string, string> = ${JSON.stringify(polylines, null, 2)};

export const BAKED_STOP_NAMES: Record<string, string> = ${JSON.stringify(stopNames, null, 2)};

export const BAKED_STOPS = ${JSON.stringify(stops, null, 2)} as const;
`;

const outPath = new URL('../assets/ttc-baked.ts', import.meta.url).pathname;
await Bun.write(outPath, output);
console.log(`\nWritten to ${outPath}`);
